# Generated by Django 2.1 on 2018-08-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontOffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='accountName',
            field=models.CharField(max_length=20, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='client',
            name='civilStatus',
            field=models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('WI', 'Widowed'), ('LS', 'Legally Separated')], max_length=20, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientPhoto',
            field=models.ImageField(upload_to='clients/images/%Y-%m-%d/', verbose_name='Client Photo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientSignature',
            field=models.ImageField(upload_to='clients/signatures/%Y-%m-%d/', verbose_name='Signature Photo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mailingAddress1',
            field=models.TextField(verbose_name='Mailing Address 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mailingAddress2',
            field=models.TextField(blank=True, default='', verbose_name='Mailing Address 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='middleName',
            field=models.CharField(max_length=20, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthlyIncome',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monthly Income'),
        ),
        migrations.AlterField(
            model_name='client',
            name='suffix',
            field=models.CharField(blank=True, max_length=3, verbose_name='Suffix'),
        ),
    ]
