# Generated by Django 2.1 on 2018-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontOffice', '0002_auto_20180816_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='civilStatus',
            field=models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('WI', 'Widowed'), ('LS', 'Legally Separated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NE', 'N/A')], max_length=6),
        ),
    ]
