# Generated by Django 2.1 on 2018-08-28 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('input_text', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Post Creation')),
                ('date_post', models.DateTimeField(default=datetime.datetime(2018, 8, 28, 9, 34, 35, 935174), verbose_name='Date of Posting')),
                ('post_status', models.BooleanField(default=False)),
            ],
        ),
    ]
