# Generated by Django 2.1 on 2018-08-28 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 9, 34, 46, 90287), verbose_name='Date of Posting'),
        ),
    ]
