# Generated by Django 2.1 on 2018-08-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='text',
            new_name='input_text',
        ),
    ]
