# Generated by Django 2.1 on 2018-08-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20180815_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
    ]
