# Generated by Django 2.1 on 2018-08-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20180815_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='input_text',
            field=models.TextField(),
        ),
    ]
