# Generated by Django 2.1 on 2018-08-28 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20180828_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateTimeField(default=datetime.date(2018, 8, 28), verbose_name='Date of Posting'),
        ),
    ]
