# Generated by Django 2.1 on 2018-08-15 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_auto_20180815_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
