# Generated by Django 2.1 on 2018-08-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20180815_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='post_status',
            field=models.BooleanField(default=False),
        ),
    ]
