# Generated by Django 2.1 on 2018-08-15 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_announcement_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Post Creation'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 15, 50, 46, 471156), verbose_name='Date of Posting'),
        ),
    ]
