# Generated by Django 2.1 on 2018-08-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20180828_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='input_text',
            field=models.TextField(verbose_name='Post Body'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='post_status',
            field=models.BooleanField(default=False, verbose_name='Post Status'),
        ),
    ]
