# Generated by Django 2.1 on 2018-08-15 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20180815_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 15, 50, 49, 960319), verbose_name='Date of Posting'),
        ),
    ]
