# Generated by Django 2.1 on 2018-08-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20180828_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(auto_now=True, verbose_name='Date of Posting'),
        ),
    ]
