# Generated by Django 2.1 on 2018-08-16 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20180815_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 10, 54, 34, 18653), verbose_name='Date of Posting'),
        ),
    ]
