# Generated by Django 2.1 on 2018-08-16 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_auto_20180816_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 10, 58, 52, 423139), verbose_name='Date of Posting'),
        ),
    ]
