# Generated by Django 2.1 on 2018-08-16 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_auto_20180816_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 15, 24, 5, 313520), verbose_name='Date of Posting'),
        ),
    ]
