# Generated by Django 2.1 on 2018-08-24 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0014_auto_20180822_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 9, 57, 22, 46775), verbose_name='Date of Posting'),
        ),
    ]
