# Generated by Django 2.1 on 2018-08-24 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0015_auto_20180824_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 17, 21, 34, 280564), verbose_name='Date of Posting'),
        ),
    ]
