# Generated by Django 2.1 on 2018-08-28 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0017_auto_20180828_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 13, 55, 1, 812637)),
        ),
    ]
