# Generated by Django 2.1 on 2018-08-28 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0018_auto_20180828_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 13, 55, 25, 641771)),
        ),
    ]
