# Generated by Django 2.1 on 2018-08-28 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0020_auto_20180828_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 14, 2, 48, 610995), verbose_name='Publication Schedule'),
        ),
    ]
